QUOTES_WITH_AUTHORS = [
  ["A budget is telling your money where to go instead of wondering where it went.", "Dave Ramsey"],
  ["Do not save what is left after spending, but spend what is left after saving.", "Warren Buffett"],
  ["The habit of saving is itself an education; it fosters every virtue.", "T.T. Munger"],
  ["Beware of little expenses. A small leak will sink a great ship.", "Benjamin Franklin"],
  ["It's not your salary that makes you rich, it's your spending habits.", "Charles A. Jaffe"],
  ["Every dollar you save is a dollar you earn.", "Sterling W. Sill"],
  ["Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.", "Dave Ramsey"],
  ["A penny saved is a penny earned.", "Benjamin Franklin"],
  ["The art is not in making money, but in keeping it.", "Proverb"],
  ["Too many people spend money they haven't earned to buy things they don't want to impress people they don't like.", "Will Rogers"],
  ["Never spend your money before you have it.", "Thomas Jefferson"],
  ["Money looks better in the bank than on your feet.", "Sophia Amoruso"],
  ["The secret to wealth is simple: spend less than you earn and invest the difference.", "David Chilton"],
  ["You must gain control over your money or the lack of it will forever control you.", "Dave Ramsey"],
  ["Wealth consists not in having great possessions, but in having few wants.", "Epictetus"],
  ["A wise person should have money in their head, but not in their heart.", "Jonathan Swift"],
  ["Don't tell me what you value. Show me your budget, and I'll tell you what you value.", "Joe Biden"],
  ["An investment in knowledge pays the best interest.", "Benjamin Franklin"],
  ["The goal isn't more money. The goal is living life on your terms.", "Chris Brogan"],
  ["Rich people stay rich by living like they're broke. Broke people stay broke by living like they're rich.", "Dave Ramsey"],
  ["It is not the man who has too little, but the man who craves more, that is poor.", "Seneca"],
  ["Money is a terrible master but an excellent servant.", "P.T. Barnum"],
  ["The quickest way to double your money is to fold it in half and put it back in your pocket.", "Will Rogers"],
  ["Budget: a mathematical confirmation of your suspicions.", "A.A. Latimer"],
  ["The best time to start saving was yesterday. The next best time is today.", "Proverb"],
  ["Wealth is the ability to fully experience life.", "Henry David Thoreau"],
  ["He who buys what he does not need steals from himself.", "Swedish Proverb"],
  ["A budget doesn't limit your freedom. It gives you freedom.", "Rachel Cruze"],
  ["Saving is a very fine thing. Especially when your parents have done it for you.", "Winston Churchill"],
  ["Frugality includes all the other virtues.", "Cicero"],
  ["Money saved is money earned twice.", "Proverb"],
  ["Live below your means but within your needs.", "Suze Orman"],
  ["Small daily improvements over time lead to stunning financial results.", "Robin Sharma"],
  ["The more you save, the more freedom you have.", "T. Harv Eker"],
  ["Spend wisely, save consistently, and your future self will thank you.", "Proverb"],
  ["Financial fitness is not a pipe dream or a state of mind. It's a reality if you are willing to pursue it.", "Will Robinson"],
  ["There is no dignity quite so impressive as living within your means.", "Calvin Coolidge"],
  ["Money grows on the tree of persistence.", "Japanese Proverb"],
  ["The only way to permanently change the temperature in the room is to reset the thermostat. The only way to change your financial success is to reset your financial thermostat.", "T. Harv Eker"],
  ["If you want to be wealthy, study wealth. If you want to be happy, study happiness.", "Jim Rohn"],
  ["A simple fact that is hard to learn is that the time to save money is when you have some.", "Joe Moore"],
  ["When you understand that your self-worth is not determined by your net-worth, then you'll have financial freedom.", "Suze Orman"],
  ["Don't go broke trying to look rich.", "Proverb"],
  ["You don't have to be a miser, just be wiser with your money.", "Proverb"],
  ["Budgeting has only one rule: do not go over budget.", "Leslie Tayne"],
  ["Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", "Ayn Rand"],
  ["The way to build your savings is by spending less each month.", "Suze Orman"],
  ["Know what you own, and know why you own it.", "Peter Lynch"],
  ["Setting goals is the first step in turning the invisible into the visible.", "Tony Robbins"],
  ["Discipline is the bridge between goals and accomplishment.", "Jim Rohn"],
  ["Every morning brings new potential, but if you dwell on the misfortunes of the day before, you tend to overlook tremendous opportunities.", "Harvey Mackay"],
  ["Formal education will make you a living; self-education will make you a fortune.", "Jim Rohn"],
  ["A budget is more than just a series of numbers on a page; it is an embodiment of our values.", "Barack Obama"],
  ["Financial independence is about having more choices.", "Robert Kiyosaki"],
  ["The lack of money is the root of all evil.", "Mark Twain"],
  ["Money without financial intelligence is money soon gone.", "Robert Kiyosaki"],
  ["Opportunity is missed by most people because it is dressed in overalls and looks like work.", "Thomas Edison"],
  ["A big part of financial freedom is having your heart and mind free from worry about the what-ifs of life.", "Suze Orman"],
  ["If you don't find a way to make money while you sleep, you will work until you die.", "Warren Buffett"],
  ["The individual investor should act consistently as an investor and not as a speculator.", "Ben Graham"],
  ["Invest in as much of yourself as you can. You are your own biggest asset by far.", "Warren Buffett"],
  ["Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.", "Warren Buffett"],
  ["Compound interest is the eighth wonder of the world. He who understands it, earns it. He who doesn't, pays it.", "Albert Einstein"],
  ["Wealth is not about having a lot of money; it's about having a lot of options.", "Chris Rock"],
  ["You try to be greedy when others are fearful, and fearful when others are greedy.", "Warren Buffett"],
  ["How many millionaires do you know who have become wealthy by investing in savings accounts?", "Robert G. Allen"],
  ["If you want to reap financial blessings, you have to sow financially.", "Joel Osteen"],
  ["It's good to have money and the things that money can buy, but check once in a while that you haven't lost the things money can't buy.", "George Lorimer"],
  ["The stock market is a device for transferring money from the impatient to the patient.", "Warren Buffett"],
  ["Price is what you pay. Value is what you get.", "Warren Buffett"],
  ["Money is usually attracted, not pursued.", "Jim Rohn"],
  ["Financial freedom is available to those who learn about it and work for it.", "Robert Kiyosaki"],
  ["I'd like to live as a poor man with lots of money.", "Pablo Picasso"],
  ["Happiness is not in the mere possession of money; it lies in the joy of achievement.", "Franklin D. Roosevelt"],
  ["You can be young without money, but you can't be old without it.", "Tennessee Williams"],
  ["Not everything that can be counted counts, and not everything that counts can be counted.", "William Bruce Cameron"],
  ["Empty pockets never held anyone back. Only empty heads and empty hearts can do that.", "Norman Vincent Peale"],
  ["Before you speak, listen. Before you spend, earn. Before you criticize, wait. Before you quit, try.", "William Arthur Ward"],
  ["The only difference between a rich person and a poor person is how they use their time.", "Robert Kiyosaki"],
  ["People who cannot control their spending are slaves to their possessions.", "Proverb"],
  ["Expect the best. Prepare for the worst. Capitalize on what comes.", "Zig Ziglar"],
  ["If we command our wealth, we shall be rich and free. If our wealth commands us, we are poor indeed.", "Edmund Burke"],
  ["Make money your servant, not your master.", "Proverb"],
  ["What you do today can improve all your tomorrows.", "Ralph Marston"],
  ["The best investment you can make is in yourself.", "Warren Buffett"],
  ["Don't let the fear of losing be greater than the excitement of winning.", "Robert Kiyosaki"],
  ["It's how you deal with failure that determines how you achieve success.", "David Feherty"],
  ["Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"],
  ["A journey of a thousand miles begins with a single step.", "Lao Tzu"],
  ["He that has little and wants less is richer than he that has much and wants more.", "Charles Caleb Colton"],
  ["Being rich is having money; being wealthy is having time.", "Margaret Bonnano"],
  ["Do what you love and the money will follow.", "Marsha Sinetar"],
  ["Stop buying things you don't need to impress people you don't even like.", "Suze Orman"],
  ["Budgeting is for everyone who wants to ensure that their money is enough.", "Proverb"],
  ["The more your money works for you, the less you have to work for money.", "Idowu Koyenikan"],
  ["Financial security is like a three-legged stool resting on savings, insurance, and investments.", "Proverb"],
  ["Wealth is not his that has it, but his that enjoys it.", "Benjamin Franklin"],
  ["Annual income twenty pounds, annual expenditure nineteen six, result happiness.", "Charles Dickens"],
  ["Annual income twenty pounds, annual expenditure twenty pounds ought and six, result misery.", "Charles Dickens"],
  ["Money often costs too much.", "Ralph Waldo Emerson"],
  ["The safe way to double your money is to fold it over once and put it in your pocket.", "Kin Hubbard"],
  ["A fool and his money are soon parted.", "Thomas Tusser"],
  ["Time is more valuable than money. You can get more money, but you cannot get more time.", "Jim Rohn"],
  ["Don't save what's left after spending; spend what's left after saving.", "Warren Buffett"],
  ["It takes as much energy to wish as it does to plan.", "Eleanor Roosevelt"],
  ["You don't have to see the whole staircase, just take the first step.", "Martin Luther King Jr."],
  ["The best way to predict the future is to create it.", "Peter Drucker"],
  ["Prosperity is not without many fears and disasters; adversity is not without comforts and hopes.", "Francis Bacon"],
  ["He who loses money, loses much; he who loses a friend, loses much more; he who loses faith, loses all.", "Eleanor Roosevelt"],
  ["Wise spending is part of wise investing. And it's never too late to start.", "Rhonda Katz"],
  ["A bargain ain't a bargain unless it's something you need.", "Sidney Carroll"],
  ["You can't build wealth if you keep buying things you don't need.", "Proverb"],
  ["The habit of managing your money is more important than the amount.", "T. Harv Eker"],
  ["Debt is the worst poverty.", "Thomas Fuller"],
  ["Interest works against you or for you. Your choice.", "Proverb"],
  ["Don't let money run your life, let money help you run your life better.", "John Rampton"],
  ["Be thankful for what you have; you'll end up having more.", "Oprah Winfrey"],
  ["The greatest wealth is to live content with little.", "Plato"],
  ["It is better to have a permanent income than to be fascinating.", "Oscar Wilde"],
  ["A man who both spends and saves money is the happiest man, because he has both enjoyments.", "Samuel Johnson"],
  ["Contentment is natural wealth; luxury is artificial poverty.", "Socrates"],
  ["Enough is a feast.", "Buddhist Proverb"],
  ["He who gathers money little by little makes it grow.", "Proverbs 13:11"],
  ["Industry is the mother of good luck.", "Benjamin Franklin"],
  ["Many folks think they aren't good at earning money, when what they don't know is how to use it.", "Frank A. Clark"],
  ["Money is like a sixth sense without which you cannot make a complete use of the other five.", "W. Somerset Maugham"],
  ["Money isn't everything, but it sure keeps you in touch with your children.", "J. Paul Getty"],
  ["My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.", "Steve Jobs"],
  ["Never confuse the size of your paycheck with the size of your talent.", "Marlon Brando"],
  ["Never depend on a single income. Make investment to create a second source.", "Warren Buffett"],
  ["Only buy something that you'd be perfectly happy to hold if the market shut down for ten years.", "Warren Buffett"],
  ["Persistence is to the character of man as carbon is to steel.", "Napoleon Hill"],
  ["Prosperity is a way of living and thinking, and not just money or things.", "Eric Butterworth"],
  ["Rich is not the one who has much, but the one who needs little.", "Proverb"],
  ["That man is richest whose pleasures are cheapest.", "Henry David Thoreau"],
  ["The man who does more than he is paid for will soon be paid for more than he does.", "Napoleon Hill"],
  ["The person who doesn't know where his next dollar is coming from usually doesn't know where his last dollar went.", "Proverb"],
  ["The rich invest in time, the poor invest in money.", "Warren Buffett"],
  ["The speed of your success is limited only by your dedication and what you're willing to sacrifice.", "Nathan W. Morris"],
  ["There are people who have money and people who are rich.", "Coco Chanel"],
  ["Try to save something while your salary is small; it's impossible to save after you begin to earn more.", "Jack Benny"],
  ["Waste neither time nor money, but make the best use of both.", "Benjamin Franklin"],
  ["We make a living by what we get, but we make a life by what we give.", "Winston Churchill"],
  ["When prosperity comes, do not use all of it.", "Confucius"],
  ["Wise men learn by other men's mistakes, fools by their own.", "H.G. Bohn"],
  ["Without continual growth and progress, such words as improvement, achievement, and success have no meaning.", "Benjamin Franklin"],
  ["Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones.", "Benjamin Franklin"],
  ["Savings, remember, is the prerequisite of investment.", "John Maynard Keynes"],
  ["It's not how much money you make, but how much money you keep.", "Robert Kiyosaki"],
  ["The best thing money can buy is financial freedom.", "Rob Berger"],
  ["A good financial plan is a road map that shows us exactly how the choices we make today will affect our future.", "Alexa Von Tobel"],
  ["Broke is temporary. Poor is a state of mind.", "Robert Kiyosaki"],
  ["Financial freedom is freedom from fear.", "Robert Kiyosaki"],
  ["If you would be wealthy, think of saving as well as getting.", "Benjamin Franklin"],
  ["Many people take no care of their money till they come nearly to the end of it.", "Johann Wolfgang von Goethe"],
  ["Money, like emotions, is something you must control to keep your life on the right track.", "Natasha Munson"],
  ["Never spend money before you have earned it.", "Thomas Jefferson"],
  ["Debt is like any other trap: easy enough to get into, but hard enough to get out of.", "Josh Billings"],
  ["More people should learn to tell their dollars where to go instead of asking them where they went.", "Roger Babson"],
  ["Too many people buy things they don't need with money they don't have to impress people they don't know.", "Dave Ramsey"],
  ["A budget tells your money where to go; without one you wonder where it went.", "Dave Ramsey"],
  ["Financial health is not a destination but a journey of consistent habits.", "Proverb"],
  ["Every penny counts when you're building something great.", "Proverb"],
  ["Don't sacrifice your future for temporary pleasures today.", "Robert Kiyosaki"],
  ["Your wallet is a reflection of your priorities.", "Proverb"],
  ["Great fortunes are built one smart decision at a time.", "Proverb"],
  ["Tracking your spending is the first step to transforming it.", "Dave Ramsey"],
  ["The money you don't spend is the most powerful money you have.", "Proverb"],
  ["Building wealth requires patience, discipline, and a little bit of math.", "Proverb"],
  ["Today's small savings are tomorrow's big opportunities.", "Proverb"],
  ["Freedom is not free. It is paid for with smart financial decisions.", "Proverb"],
  ["A clear budget clears the mind.", "Proverb"],
  ["Money management is a skill that pays dividends for life.", "Proverb"],
  ["The richest person is not who has the most, but who needs the least.", "Proverb"],
  ["Your financial future is built by what you do today, not tomorrow.", "Robert Kiyosaki"],
  ["Saving isn't about depriving yourself. It's about deciding what matters most.", "Proverb"],
  ["Every financial goal starts with a single tracked expense.", "Proverb"],
  ["The difference between rich and wealthy is discipline.", "Proverb"],
  ["Control your money or it will control you.", "Dave Ramsey"],
  ["Pay yourself first, then pay your bills.", "George S. Clason"],
  ["A dollar saved today is worth more than a dollar earned tomorrow.", "Proverb"],
  ["Smart money moves today create comfortable tomorrows.", "Proverb"],
  ["Budgeting is the foundation upon which financial dreams are built.", "Dave Ramsey"],
  ["When you budget, you give every dollar a purpose.", "Dave Ramsey"],
  ["Financial wellness is a marathon, not a sprint.", "Proverb"],
  ["The greatest gift you can give your family is financial stability.", "Suze Orman"],
  ["Consistent small steps lead to massive financial gains.", "Darren Hardy"],
  ["Live for today, plan for tomorrow, and save for the unexpected.", "Proverb"],
  ["Money management isn't about restriction; it's about intention.", "Proverb"],
  ["The secret to financial success: earn more, spend less, invest the rest.", "Proverb"],
  ["Your budget is your permission slip to spend guilt-free on what matters.", "Dave Ramsey"],
  ["Wealth whispers. It doesn't shout.", "Proverb"],
  ["Start where you are. Use what you have. Save what you can.", "Arthur Ashe"],
  ["The first step toward wealth is learning to be a good steward of what you already have.", "T. Harv Eker"],
  ["Financial goals without a plan are just wishes.", "Antoine de Saint-Exupery"],
  ["A budget is your roadmap to financial peace of mind.", "Dave Ramsey"],
  ["Prosperity belongs to those who learn new things the fastest.", "Paul Zane Pilzer"],
  ["Your income is your most powerful wealth-building tool. Don't waste it.", "Dave Ramsey"],
  ["The best financial decision you can make is to stop procrastinating.", "Proverb"],
  ["Money flows to those who respect it and manage it well.", "Idowu Koyenikan"]
]

# If quotes exist without authors, backfill them
if Quote.count > 0 && Quote.where(quote_author: [nil, ""]).exists?
  puts "Backfilling authors for #{Quote.where(quote_author: [nil, '']).count} quotes..."
  QUOTES_WITH_AUTHORS.each do |text, author|
    quote = Quote.find_by(quote_text: text, quote_author: [nil, ""])
    quote.update!(quote_author: author) if quote
  end
  puts "Done! Authors backfilled."
elsif Quote.count == 0
  puts "Seeding #{QUOTES_WITH_AUTHORS.length} quotes with authors..."
  QUOTES_WITH_AUTHORS.each do |text, author|
    Quote.create!(quote_text: text, quote_author: author, is_active: true)
  end
  puts "Done! #{Quote.count} quotes created."
else
  puts "Quotes already exist with authors (#{Quote.count}). Skipping seed."
end
