import { Controller } from "@hotwired/stimulus"

const QUOTES = [
  "A budget is telling your money where to go instead of wondering where it went.",
  "Do not save what is left after spending, but spend what is left after saving.",
  "The habit of saving is itself an education; it fosters every virtue.",
  "Beware of little expenses. A small leak will sink a great ship.",
  "It's not your salary that makes you rich, it's your spending habits.",
  "Every dollar you save is a dollar you earn.",
  "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.",
  "A penny saved is a penny earned.",
  "The art is not in making money, but in keeping it.",
  "Too many people spend money they haven't earned to buy things they don't want to impress people they don't like.",
  "Never spend your money before you have it.",
  "Money looks better in the bank than on your feet.",
  "The secret to wealth is simple: spend less than you earn and invest the difference.",
  "You must gain control over your money or the lack of it will forever control you.",
  "Wealth consists not in having great possessions, but in having few wants.",
  "A wise person should have money in their head, but not in their heart.",
  "Don't tell me what you value. Show me your budget, and I'll tell you what you value.",
  "An investment in knowledge pays the best interest.",
  "The goal isn't more money. The goal is living life on your terms.",
  "Rich people stay rich by living like they're broke. Broke people stay broke by living like they're rich.",
  "It is not the man who has too little, but the man who craves more, that is poor.",
  "Money is a terrible master but an excellent servant.",
  "The quickest way to double your money is to fold it in half and put it back in your pocket.",
  "Budget: a mathematical confirmation of your suspicions.",
  "The best time to start saving was yesterday. The next best time is today.",
  "Wealth is the ability to fully experience life.",
  "He who buys what he does not need steals from himself.",
  "A budget doesn't limit your freedom. It gives you freedom.",
  "Saving is a very fine thing. Especially when your parents have done it for you.",
  "Frugality includes all the other virtues.",
  "Money saved is money earned twice.",
  "Live below your means but within your needs.",
  "Small daily improvements over time lead to stunning financial results.",
  "The more you save, the more freedom you have.",
  "Spend wisely, save consistently, and your future self will thank you.",
  "Financial fitness is not a pipe dream or a state of mind. It's a reality if you are willing to pursue it.",
  "There is no dignity quite so impressive as living within your means.",
  "Money grows on the tree of persistence.",
  "The only way to permanently change the temperature in the room is to reset the thermostat. The only way to change your financial success is to reset your financial thermostat.",
  "If you want to be wealthy, study wealth. If you want to be happy, study happiness.",
  "A simple fact that is hard to learn is that the time to save money is when you have some.",
  "When you understand that your self-worth is not determined by your net-worth, then you'll have financial freedom.",
  "Don't go broke trying to look rich.",
  "You don't have to be a miser, just be wiser with your money.",
  "Budgeting has only one rule: do not go over budget.",
  "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
  "The way to build your savings is by spending less each month.",
  "Know what you own, and know why you own it.",
  "Setting goals is the first step in turning the invisible into the visible.",
  "Discipline is the bridge between goals and accomplishment.",
  "Every morning brings new potential, but if you dwell on the misfortunes of the day before, you tend to overlook tremendous opportunities.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "A budget is more than just a series of numbers on a page; it is an embodiment of our values.",
  "Financial independence is about having more choices.",
  "The lack of money is the root of all evil.",
  "Money without financial intelligence is money soon gone.",
  "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
  "A big part of financial freedom is having your heart and mind free from worry about the what-ifs of life.",
  "If you don't find a way to make money while you sleep, you will work until you die.",
  "The individual investor should act consistently as an investor and not as a speculator.",
  "Invest in as much of yourself as you can. You are your own biggest asset by far.",
  "Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.",
  "Compound interest is the eighth wonder of the world. He who understands it, earns it. He who doesn't, pays it.",
  "Wealth is not about having a lot of money; it's about having a lot of options.",
  "You try to be greedy when others are fearful, and fearful when others are greedy.",
  "How many millionaires do you know who have become wealthy by investing in savings accounts?",
  "If you want to reap financial blessings, you have to sow financially.",
  "It's good to have money and the things that money can buy, but check once in a while that you haven't lost the things money can't buy.",
  "The stock market is a device for transferring money from the impatient to the patient.",
  "Price is what you pay. Value is what you get.",
  "Money is usually attracted, not pursued.",
  "Financial freedom is available to those who learn about it and work for it.",
  "I'd like to live as a poor man with lots of money.",
  "Happiness is not in the mere possession of money; it lies in the joy of achievement.",
  "You can be young without money, but you can't be old without it.",
  "Not everything that can be counted counts, and not everything that counts can be counted.",
  "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.",
  "Before you speak, listen. Before you spend, earn. Before you criticize, wait. Before you quit, try.",
  "The only difference between a rich person and a poor person is how they use their time.",
  "People who cannot control their spending are slaves to their possessions.",
  "Expect the best. Prepare for the worst. Capitalize on what comes.",
  "If we command our wealth, we shall be rich and free. If our wealth commands us, we are poor indeed.",
  "Make money your servant, not your master.",
  "What you do today can improve all your tomorrows.",
  "The best investment you can make is in yourself.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "It's how you deal with failure that determines how you achieve success.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "A journey of a thousand miles begins with a single step.",
  "He that has little and wants less is richer than he that has much and wants more.",
  "Being rich is having money; being wealthy is having time.",
  "Do what you love and the money will follow.",
  "Stop buying things you don't need to impress people you don't even like.",
  "Budgeting is for everyone who wants to ensure that their money is enough.",
  "The more your money works for you, the less you have to work for money.",
  "Financial security is like a three-legged stool resting on savings, insurance, and investments.",
  "Wealth is not his that has it, but his that enjoys it.",
  "Annual income twenty pounds, annual expenditure nineteen six, result happiness.",
  "Annual income twenty pounds, annual expenditure twenty pounds ought and six, result misery.",
  "Money often costs too much.",
  "The safe way to double your money is to fold it over once and put it in your pocket.",
  "A fool and his money are soon parted.",
  "Time is more valuable than money. You can get more money, but you cannot get more time.",
  "Don't save what's left after spending; spend what's left after saving.",
  "It takes as much energy to wish as it does to plan.",
  "You don't have to see the whole staircase, just take the first step.",
  "The best way to predict the future is to create it.",
  "Prosperity is not without many fears and disasters; adversity is not without comforts and hopes.",
  "He who loses money, loses much; he who loses a friend, loses much more; he who loses faith, loses all.",
  "Wise spending is part of wise investing. And it's never too late to start.",
  "A bargain ain't a bargain unless it's something you need.",
  "You can't build wealth if you keep buying things you don't need.",
  "The habit of managing your money is more important than the amount.",
  "Debt is the worst poverty.",
  "Interest works against you or for you. Your choice.",
  "Don't let money run your life, let money help you run your life better.",
  "Be thankful for what you have; you'll end up having more.",
  "The greatest wealth is to live content with little.",
  "It is better to have a permanent income than to be fascinating.",
  "A man who both spends and saves money is the happiest man, because he has both enjoyments.",
  "Contentment is natural wealth; luxury is artificial poverty.",
  "Enough is a feast.",
  "He who gathers money little by little makes it grow.",
  "Industry is the mother of good luck.",
  "Many folks think they aren't good at earning money, when what they don't know is how to use it.",
  "Money is like a sixth sense without which you cannot make a complete use of the other five.",
  "Money isn't everything, but it sure keeps you in touch with your children.",
  "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.",
  "Never confuse the size of your paycheck with the size of your talent.",
  "Never depend on a single income. Make investment to create a second source.",
  "Only buy something that you'd be perfectly happy to hold if the market shut down for ten years.",
  "Persistence is to the character of man as carbon is to steel.",
  "Prosperity is a way of living and thinking, and not just money or things.",
  "Rich is not the one who has much, but the one who needs little.",
  "That man is richest whose pleasures are cheapest.",
  "The man who does more than he is paid for will soon be paid for more than he does.",
  "The person who doesn't know where his next dollar is coming from usually doesn't know where his last dollar went.",
  "The rich invest in time, the poor invest in money.",
  "The speed of your success is limited only by your dedication and what you're willing to sacrifice.",
  "There are people who have money and people who are rich.",
  "Try to save something while your salary is small; it's impossible to save after you begin to earn more.",
  "Waste neither time nor money, but make the best use of both.",
  "We make a living by what we get, but we make a life by what we give.",
  "When prosperity comes, do not use all of it.",
  "Wise men learn by other men's mistakes, fools by their own.",
  "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.",
  "Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones.",
  "Savings, remember, is the prerequisite of investment.",
  "It's not how much money you make, but how much money you keep.",
  "The best thing money can buy is financial freedom.",
  "A good financial plan is a road map that shows us exactly how the choices we make today will affect our future.",
  "Broke is temporary. Poor is a state of mind.",
  "Financial freedom is freedom from fear.",
  "If you would be wealthy, think of saving as well as getting.",
  "Many people take no care of their money till they come nearly to the end of it.",
  "Money, like emotions, is something you must control to keep your life on the right track.",
  "Never spend money before you have earned it.",
  "Debt is like any other trap: easy enough to get into, but hard enough to get out of.",
  "More people should learn to tell their dollars where to go instead of asking them where they went.",
  "Too many people buy things they don't need with money they don't have to impress people they don't know.",
  "A budget tells your money where to go; without one you wonder where it went.",
  "Financial health is not a destination but a journey of consistent habits.",
  "Every penny counts when you're building something great.",
  "Don't sacrifice your future for temporary pleasures today.",
  "Your wallet is a reflection of your priorities.",
  "Great fortunes are built one smart decision at a time.",
  "Tracking your spending is the first step to transforming it.",
  "The money you don't spend is the most powerful money you have.",
  "Building wealth requires patience, discipline, and a little bit of math.",
  "Today's small savings are tomorrow's big opportunities.",
  "Freedom is not free. It is paid for with smart financial decisions.",
  "A clear budget clears the mind.",
  "Money management is a skill that pays dividends for life.",
  "The richest person is not who has the most, but who needs the least.",
  "Your financial future is built by what you do today, not tomorrow.",
  "Saving isn't about depriving yourself. It's about deciding what matters most.",
  "Every financial goal starts with a single tracked expense.",
  "The difference between rich and wealthy is discipline.",
  "Control your money or it will control you.",
  "Pay yourself first, then pay your bills.",
  "A dollar saved today is worth more than a dollar earned tomorrow.",
  "Smart money moves today create comfortable tomorrows.",
  "Budgeting is the foundation upon which financial dreams are built.",
  "When you budget, you give every dollar a purpose.",
  "Financial wellness is a marathon, not a sprint.",
  "The greatest gift you can give your family is financial stability.",
  "Consistent small steps lead to massive financial gains.",
  "Live for today, plan for tomorrow, and save for the unexpected.",
  "Money management isn't about restriction; it's about intention.",
  "The secret to financial success: earn more, spend less, invest the rest.",
  "Your budget is your permission slip to spend guilt-free on what matters.",
  "Wealth whispers. It doesn't shout.",
  "Start where you are. Use what you have. Save what you can.",
  "The first step toward wealth is learning to be a good steward of what you already have.",
  "Financial goals without a plan are just wishes.",
  "A budget is your roadmap to financial peace of mind.",
  "Prosperity belongs to those who learn new things the fastest.",
  "Your income is your most powerful wealth-building tool. Don't waste it.",
  "The best financial decision you can make is to stop procrastinating.",
  "Money flows to those who respect it and manage it well."
]

export default class extends Controller {
  static targets = ["text", "toggle"]

  connect() {
    this.showQuotes = localStorage.getItem("showQuotes") !== "false"
    this._applyVisibility()
    if (this.showQuotes) this._showNext()
  }

  toggle() {
    this.showQuotes = !this.showQuotes
    localStorage.setItem("showQuotes", String(this.showQuotes))
    this._applyVisibility()
    if (this.showQuotes) this._showNext()
  }

  _showNext() {
    let idx = parseInt(localStorage.getItem("quoteIndex") || "0", 10)
    if (isNaN(idx) || idx < 0 || idx >= QUOTES.length) idx = 0
    this.textTarget.textContent = `"${QUOTES[idx]}"`
    localStorage.setItem("quoteIndex", String((idx + 1) % QUOTES.length))
  }

  _applyVisibility() {
    if (this.showQuotes) {
      this.textTarget.classList.remove("hidden")
      this.toggleTarget.title = "Hide quotes"
      this.toggleTarget.innerHTML = `<svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.878 9.878L3 3m6.878 6.878L21 21"/></svg>`
    } else {
      this.textTarget.classList.add("hidden")
      this.toggleTarget.title = "Show quotes"
      this.toggleTarget.innerHTML = `<svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>`
    }
  }
}
